### ISSUE TITLE
Create new .Net 6.0 project for VEDriversLite.NeblioAPI and upgrade dependent projects.

### ISSUE THREAD

**Issue by VenkataRoundSqr** [fyziktom/VirtualEconomyFramework#123]
Idea is to move Neblio API folder and file in it that is NeblioRestAPI to a separate project. This is to avoid dependency in referencing or downloading entire VEDriversLite project if we have to work with NeblioAPI.

@fyziktom please add more details if needed.

**Comment by fyziktom** [comment]
Solved. Package was published with versions 0.3.0
