### ISSUE TITLE
Clean form VS preview v Galerii

### ISSUE THREAD

**Issue by ghost** [fyziktom/VirtualEconomyFramework#173]
# Clean form nebo přejití do Galerie po uploadu nového NFT

Po dokončení uploadu nového NFT do Gallery se v tuto chvíli u možnosti uploadu nového NFT zobrazí/nahrají předchozí files a texty včetně tagů. Místo toho nabídnout uživateli 2 volby:

--> Modal (1) s možností volby jít se podívat do Galerie na výsledný upload (1a) nebo nahrát nové NFT (1b).
1a = odkaz do Galerie na preview posledního uploadovaného NFT
1b = nabídne uživateli další možnost (2).

--> Modal (2) s výběrem mezi Clean form (2a) nebo použitím informací z posledního uploadu (2b).
2a = vymaže informace z posledního uploadu a vytvoří Clean form pro zcela nové NFT
2b = upload nového NFT s použitím informací z posledního uploadu

```mermaid
graph TD
A[Finished uploading new NFT] --> B[1 - What do you want to do next?]
B -->|"1a - Go to Gallery"| C[Show preview of the last uploaded NFT in the Gallery]
B -->|"1b - Upload new NFT"| D[2 - Do you want to start fresh or use the data from the last upload?]
D --> E[2a - I want a clean slate]
D --> F[2b - Upload with last used data]
```

## Design idea (použít stejné barvy jako uvnitř appky):

Modal 1
![Modal 1](https://user-images.githubusercontent.com/127226345/224518572-c9e71575-f6cc-46b0-810f-b53db7720d78.png)

Modal 2
![Modal 2](https://user-images.githubusercontent.com/127226345/224519411-a179a60b-3d8a-441e-91eb-1aed79225018.png)

**Comment by fyziktom** [comment]
První verze je k dispozici online:

![obrazek](https://user-images.githubusercontent.com/78320021/231476037-2d5975ee-765d-428a-9046-8d3eb10bd46e.png)

![obrazek](https://user-images.githubusercontent.com/78320021/231476196-f717cefb-b3f4-49d6-9e97-03d2a9c127f9.png)

Ještě by stálo za to vymyslet jak přidat "clean form" tlačítka na jednotlivé kroky v rámci mintovacích formulářů. 
Na základě předešlé debaty byl návrh mít jedno tlačítko v rámci minitngtoolbaru (to kde je tlačítko Load From template) a to by po kliknutí otevřelo dotaz, jestli se má vymazat jen aktuální formulář a nebo všechny mintovací formuláře (myšleno v rámci mintování daného typu NFT všechny kroky (Upload Data, DataInfoForm, apod,).

**Comment by fyziktom** [comment]
Bylo to přidáno v posledním větším mergi.
