### ISSUE TITLE
Pagination - Transaction history

### ISSUE THREAD

**Issue by ghost** [fyziktom/VirtualEconomyFramework#176]
# Transaction history
Jedná se jen o malou úpravu, ale vyplatila by se.

Jeden z dropdownů na Home page je Transaction history. Když ho uživatel otevře, ukáže se seznam 7 položek a pod ním pagination.

Tato pagination v tuto chvíli ukazuje 3 strany seznamu přestože je v něm jen 7 položek = zaplněná je jen 1 strana.

## Návrh
Pokud možno upravit funkci pagination tak, aby byla schopná spočítat celý seznam a uživateli ukázat, kolik stran v seznamu skutečně existuje.

Tím se pravděpodobně vyřeší i issue, kdy v momentě jak uživatel momentálně klikne na další stranu, která je ale prázdná, celý seznam včetně pagination zmizí a uživateli nezbývá nic jiného než přejít na jinou stránku a vrátit se zpět na Home page, aby byl seznam opět viditelný.

https://user-images.githubusercontent.com/127226345/224578932-9e7f7815-3dd9-4bf2-b255-e9d8f438b882.mov

**Comment by fyziktom** [comment]
It has been fixed in the last big merge
