### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by kayhantolga** [fyziktom/VirtualEconomyFramework#184]
Library Update
please use the newer version of Betalgo.OpenAI
`<PackageReference Include="Betalgo.OpenAI" Version="6.8.6" />`
https://github.com/fyziktom/VirtualEconomyFramework/blob/95b17939d763a3ad99bb6d0ab194e713df48d6bc/VirtualEconomyFramework/VEDriversLite.AI.OpenAI/VEDriversLite.AI.OpenAI.csproj#L25

**Comment by fyziktom** [comment]
will be updated with the #183
