### ISSUE TITLE
UNIT TESTING - Independent methods - Version 1

### ISSUE THREAD

**Issue by DeerajChakravarthy** [fyziktom/VirtualEconomyFramework#38]
Methods identified so far for unit testing:

SendNeblioTransaction
IsPrivateKeyValid
CheckSpendableNeblio
GetSendAmount
GetAddressNebUtxos

We are closing this work item with the unit test methods for the above methods.

**Comment by VenkataRoundSqr** [comment]
We have written unit tests using XUnit framework, have created a folder 'Neblio' under the Unit tests project(VEFrameworkUnitTest) and created one each class for a method in NeblioTransactionHelpers.cs. 
For example:
CalculateFeeTest.cs contains unit test methods to cover various test cases around calculating fee for a transaction.

@fyziktom please add more details as required.
