### ISSUE TITLE
beta.ve-nft.com - transactions list - incorrect

### ISSUE THREAD

**Issue by DeerajChakravarthy** [fyziktom/VirtualEconomyFramework#54]
1. Navigate to this page, https://beta.ve-nft.com/account
2. Click on WebPage link in the Profile card
3. https://beta.ve-nft.com/account - this link will open in a new browser tab.
4. Under the transactions list Number of transactions: displays as 2
5. The list of transactions are three. Please see the red rectangle box below.

![image](https://user-images.githubusercontent.com/19287860/150648095-1a2e621d-d55a-4820-9350-696ad2f6a178.png)

**Comment by DeerajChakravarthy** [comment]
Please see the following fix. Hope this helps.

![Fix.png](https://images.zenhubusercontent.com/61dd7cd6a8ade5c67b5d229f/04555c62-9e6e-46ea-9a14-
f0d032e3ac82)

**Comment by fyziktom** [comment]
Closing this issue. it was solved in [this pull request](https://github.com/fyziktom/VirtualEconomyFramework/pull/75)
