### ISSUE TITLE
FEATURE - Create new Coruzant.com webpage

### ISSUE THREAD

**Issue by fyziktom** [fyziktom/VirtualEconomyFramework#71]
The Coruzant.com platform starts to transform to the Blockchain. They already has own tokens [CORZT](https://explorer.nebl.io/token/La9ADonmDwxsNKJGvnRWy8gmWmeo72AEeg8cK7). These tokens will work as carrier for Articles, Profiles, Podcasts, etc.

For the display the data from these NFTs we need at first simple OnePage which will load and display the 10 newest articles and 10 newests profiles. 

When user will click to some articles or profile, it will open the details of it.

[This is branch for this issue](https://github.com/fyziktom/VirtualEconomyFramework/tree/71-coruzant-page)

**Comment by Fh-Ndiritu** [comment]
[bin.zip](https://github.com/fyziktom/VirtualEconomyFramework/files/8003088/bin.zip)
[App.zip](https://github.com/fyziktom/VirtualEconomyFramework/files/8003102/App.zip)
[Coruzant.zip](https://github.com/fyziktom/VirtualEconomyFramework/files/8003107/Coruzant.zip)

**Comment by fyziktom** [comment]
@Fh-Ndiritu , Could you please add the Markdown parsing into the articles please? 

![](https://ipfs.infura.io/ipfs/QmWBEmT1E3U7uE32R7sKW41DES1psEbTpTA36G5nraGnPd)

you have to [add this library](https://github.com/fyziktom/VirtualEconomyFramework/blob/b8eb9d95784f065f21e0e5172cac3ddcb55e7655/VirtualEconomyFramework/VENFTApp-Blazor/Components/NFTs/Posts/PostNFTDetails.razor#L2) and then [declare this](https://github.com/fyziktom/VirtualEconomyFramework/blob/b8eb9d95784f065f21e0e5172cac3ddcb55e7655/VirtualEconomyFramework/VENFTApp-Blazor/Components/NFTs/Posts/PostNFTDetails.razor#L105) and [here is usage](https://github.com/fyziktom/VirtualEconomyFramework/blob/b8eb9d95784f065f21e0e5172cac3ddcb55e7655/VirtualEconomyFramework/VENFTApp-Blazor/Components/NFTs/Posts/PostNFTDetails.razor#L39)

**Comment by fyziktom** [comment]
All [external links](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VEOnePage/Components/Social.razor#L2) should open in new tab. For the contacts or about please do it like popup for now instead of redirect to old coruzant page please.

**Comment by fyziktom** [comment]
[Ad podcasts](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VEOnePage/Components/PodcastList.razor#L8):

The NFT CoruzantProfiles which contains property should be able to open popup with the loaded podcast. Now we are using the Buzzsprout server, where Coruzant publish the podcasts. It would be better to store them on the ipfs too, but now it is done this way and we will move them later. For now, we are loading the buzzsprout podcast info from their server. Their API require the API Key, thats why we run some own support api with command which request the data and return back what we need.

It looks like this

```csharp
        public class BuzzsproutEpisodeDto
        {
            public int id { get; set; } = 0;
            public string title { get; set; } = string.Empty;
            public string audio_url { get; set; } = string.Empty;
            public string artwork_url { get; set; } = string.Empty;
            public string description { get; set; } = string.Empty;
            public string summary { get; set; } = string.Empty;
            public string artist { get; set; } = string.Empty;
            public string guid { get; set; } = string.Empty;
            public int total_plays { get; set; } = 0;
        }
        [AllowCrossSiteJsonAttribute]
        [HttpGet("GetBuzzsproutData/{profile}/{podcast}")]
        public async Task<List<BuzzsproutEpisodeDto>> GetBuzzsproutData(string profile, string podcast)
        {
            if (string.IsNullOrEmpty(profile))
                return null;

            try
            {
                var apiToken = "BUZZSPROUT_ACCOUNT_API_TOKEN";

                using (var client = new HttpClient())
                {
                    var url = $"https://www.buzzsprout.com/api/{profile}/episodes.json";

                    using (var content = new MultipartFormDataContent())
                    {
                        client.DefaultRequestHeaders.Add("Authorization", $"Token token={apiToken}");
                        var response = await client.GetAsync(url);
                        var jsonresponse = await response.Content.ReadAsStringAsync();
                        var res = JsonConvert.DeserializeObject<List<BuzzsproutEpisodeDto>>(jsonresponse);
                        if (res != null)
                        {
                            var pod = res.FirstOrDefault(p => p.id == Convert.ToInt32(podcast));
                            if (pod != null)
                                return new List<BuzzsproutEpisodeDto>() { pod };
                            else
                                return res;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error during uploading the image to the IPFS." + ex.Message);
            }
            return null;
        }
```


This is called for example [here](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VENFTApp-Blazor/Components/Coruzant/CoruzantNFTDetails.razor#L464).

The service runs on our server so we can use this now, but we will add it in this branch to the VENFT App Server later.

The Buzzsprout data are loaded to the [div tag here](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VENFTApp-Blazor/Components/Coruzant/CoruzantNFTDetails.razor#L177) and it must have [added JavaScript in external js file like here](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VENFTApp-Blazor/wwwroot/jsInterop.js#L59) and this [js file is added to the index.html](https://github.com/fyziktom/VirtualEconomyFramework/blob/e3a1d7b2a2ba433ae9e43ea586cab7d70fe7beae/VirtualEconomyFramework/VENFTApp-Blazor/wwwroot/index.html#L41).

**Comment by Fh-Ndiritu** [comment]
I added Markdig, it's a great library!

**Comment by Fh-Ndiritu** [comment]
![image](https://user-images.githubusercontent.com/98909731/153410939-26b6bb41-a03e-4a41-864c-241caaacee46.png)

I went with this for the podcasts. Feels less intrusive playing down here.

**Comment by fyziktom** [comment]
Wow, it looks really great :)

I think you could add some loading bar. When the podcast is loading, it will display just the red cross for some while and I though it is some error.

Also please check the how does it display items on the phone/small displays. I expect lots of people will browse it just on the phone.

I see the pages for profiles, articles already working. great job.

We have already 160 NFT Coruzant profiles with podcasts on the address. now we limit the load of the NFTs to speed up loading, but when it is loaded, we can start to load others on background (or do this just after you will go to "Featured" or "Podcasts" pages and then you can offer the listing of the podcasts/profiles. In the #74 you can find the way how to solve paging, etc. The example of the list [is here](https://github.com/fyziktom/VirtualEconomyFramework/blob/main/VirtualEconomyFramework/VENFTApp-Blazor/Components/Account/TransactionsList.razor)

**Comment by fyziktom** [comment]
prozatím uzavírám tuto issue. Demo funguje již delší dobu a je k dispozici na oficiální doméně coruzant: https://nft.coruzant.com

Je připravovaná další feature, která bude v rámci tohoto dema, ale na to se otevře samostatná issue.
