### ISSUE TITLE
Refactoring NeblioTransactionHelper.cs - 2

### ISSUE THREAD

**Issue by VenkataRoundSqr** [fyziktom/VirtualEconomyFramework#78]
As part of this Issue we will be refactoring rest of the methods in the class where we do not need Async/await and where there is a possibility to merge IF conditions.

Below are the changes made in NeblioTransactionHelpers.cs class.
1. Removed unnecessary Async/Await.
2. Merged few IF conditions.
3. Removed unnecessary Try/Catch blocks.
4. Removed unnecessary assignments to variables.

**Comment by VenkataRoundSqr** [comment]
Pull request is raised already and linked to this issue. Moving this issue to QA.

**Comment by fyziktom** [comment]
closing for duplicity
