### ISSUE TITLE
System is treating WithCoppies checkbox's value as checked even though it is turned off.

### ISSUE THREAD

**Issue by VenkataRoundSqr** [fyziktom/VirtualEconomyFramework#91]
Checking and then unChecking WithCoppies checkbox on New NFT screen is not getting passing in correctly.

Steps to reproduce:
1. Check the withcoppies box and fill the number of copies textbox with a value
2. UnCheck the withcoppies box and proceed with Mint

Expected:
Only one NFT should be sent for Minting

Actual:
The number of copies values are taken into consideration and that many number of NFTs are getting minted.

**Comment by fyziktom** [comment]
toto se vztahuje ke staré NFT app. Vzhledem k tomu, že ji nahradila knihovna VEBlazor a nová VENFT App není potřeba toto nyní řešit.
