### ISSUE TITLE
Add search box for TAGs

### ISSUE THREAD

**Issue by schamannnet** [fyziktom/VirtualEconomyFramework#94]
Add this search box into other pages with NFT list:
![image](https://user-images.githubusercontent.com/30752593/158472588-3d8f93eb-3f88-4ba2-a5dd-7f10430ec480.png)

[Here is the example of the NFT List with the Tag filtration](https://github.com/fyziktom/VirtualEconomyFramework/blob/dc368811b37005f151cafc1a23d13c06173cb1df/VirtualEconomyFramework/VENFTApp-Blazor/Components/NFTs/NFTList.razor#L88)

The NFT in the NFTs list is displayed based on result of the function [IsInFilter](https://github.com/fyziktom/VirtualEconomyFramework/blob/dc368811b37005f151cafc1a23d13c06173cb1df/VirtualEconomyFramework/VENFTApp-Blazor/Components/NFTs/NFTList.razor#L352).

We need to add it first in the VENFT Banner App [in here](https://github.com/fyziktom/VirtualEconomyFramework/blob/dc368811b37005f151cafc1a23d13c06173cb1df/VirtualEconomyFramework/VENFTApp-Banner/Pages/Address.razor#L116)

**Comment by fyziktom** [comment]
solved in the VEBlazor. For the VEOnePage or Banner kind of app we will use same system. It will be splited from the VEBlazor library to some smaller package.
